name: AtomicRadio
main: id.au.jsaunders.atomicradio.AtomicRadio
version: 1.0

commands:
    radio:
        description: The main command for AtomicRadio.
        usage: /<command> (dj, dj on, dj off, bc, broadcast, reload)

permissions:
    atomicradio.admin:
        description: Gives access to all radio commands
        children:
            atomicradio.status: true
        default: op
    atomicradio.use:
        description: Gives access to DJ commands